In [3]:
import numpy as np

a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a.reshape(-1,4)

ValueError: cannot reshape array of size 6 into shape (4)

In [7]:
a.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a.reshape(4,-1)

ValueError: cannot reshape array of size 6 into shape (4,newaxis)

In [9]:
a

array([1, 2, 3, 4, 5, 6])

In [10]:
a = a.reshape(2,3)

In [11]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a.reshape(-1, 1, 2)

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])